name: Publish
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main
    paths:
      - "packages/widget-react/package.json"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org/"
      - working-directory: packages/widget-react
        run: pnpm i
      - working-directory: packages/widget-react
        run: pnpm build
      - working-directory: packages/widget-react
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_ACCESS_TOKEN }}
